### ISSUE TITLE
* Keyword in steps (in the feature file) instead of Given/When/Then/And/But does not create the PDFReport

### ISSUE THREAD

**Issue by cuke4duke** [grasshopper7/extentreports-cucumber6-adapter#43]
In Sample1.zip in the src/test/resources/features/f1.feature file the keyword And is used in the step
In Sample2.zip in the src/test/resources/features/f1.feature file the keyword  * is used in the step.
The PDFReport does not get generated for extent reports in Sample2
[CucumberSample1.zip](https://github.com/grasshopper7/extentreports-cucumber6-adapter/files/7153694/CucumberSample1.zip)
[CucumberSample2.zip](https://github.com/grasshopper7/extentreports-cucumber6-adapter/files/7153695/CucumberSample2.zip)

**Comment by grasshopper7** [comment]
Are u getting some exception? If so can u add it.

**Comment by cuke4duke** [comment]
Running org.runners.RunnerTest
Sep 13, 2021 4:30:45 PM tech.grasshopper.pdf.extent.ExtentPDFCucumberReporter flush
SEVERE: An exception occurred
java.lang.IllegalArgumentException: No enum constant tech.grasshopper.pdf.pojo.cucumber.Hook.HookType.ORG.STEPDEFINITIONS.MYSTEPDEFS.SUM(INT,INT,INT)
        at java.base/java.lang.Enum.valueOf(Enum.java:240)
        at tech.grasshopper.pdf.pojo.cucumber.Hook$HookType.valueOf(Hook.java:22)
        at tech.grasshopper.pdf.extent.ExtentPDFReportDataGenerator.createScenarioHookSteps(ExtentPDFReportDataGenerator.java:82)
        at tech.grasshopper.pdf.extent.ExtentPDFReportDataGenerator.generateReportData(ExtentPDFReportDataGenerator.java:56)
        at tech.grasshopper.pdf.extent.ExtentPDFCucumberReporter.flush(ExtentPDFCucumberReporter.java:77)
        at tech.grasshopper.pdf.extent.ExtentPDFCucumberReporter.access$100(ExtentPDFCucumberReporter.java:19)
        at tech.grasshopper.pdf.extent.ExtentPDFCucumberReporter$1.onNext(ExtentPDFCucumberReporter.java:56)
        at tech.grasshopper.pdf.extent.ExtentPDFCucumberReporter$1.onNext(ExtentPDFCucumberReporter.java:49)
        at io.reactivex.rxjava3.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:310)
        at io.reactivex.rxjava3.subjects.PublishSubject.onNext(PublishSubject.java:226)
        at com.aventstack.extentreports.ReactiveSubject.onFlush(ReactiveSubject.java:83)
        at com.aventstack.extentreports.AbstractProcessor.onFlush(AbstractProcessor.java:85)
        at com.aventstack.extentreports.ExtentReports.flush(ExtentReports.java:284)
        at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter.finishReport(ExtentCucumberAdapter.java:300)
        at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter.access$600(ExtentCucumberAdapter.java:62)
        at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter$8.receive(ExtentCucumberAdapter.java:136)
        at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter$8.receive(ExtentCucumberAdapter.java:133)
        at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
        at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
        at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunFinished(CucumberExecutionContext.java:93)
        at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:74)
        at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:237)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by cuke4duke** [comment]
I have put the exception stacktrace in the Sample2.zip

**Comment by cuke4duke** [comment]
extract the CucumberSample2.zip file and run "mvn clean test"

**Comment by grasshopper7** [comment]
fixed it. will have to test as this code is also used by json plugin report. will be available in maven in a couple of days.

**Comment by cuke4duke** [comment]
Thanks for the fix.  Meanwhile can u pls post the fixed jar file here, so that I can replace temporarily in my (local) maven repository and test it.

**Comment by grasshopper7** [comment]
Uploaded 2.8.4 version. Should be replicated in Maven pretty soon

**Comment by cuke4duke** [comment]
2.8.4 Works...Tha``nks for fixing this in priority...   :)
